# Generated by Django 4.2.2 on 2023-06-18 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='text',
            new_name='app',
        ),
    ]
