# Generated by Django 4.2.2 on 2023-06-18 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_articles_options_rename_text_articles_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='app',
            field=models.CharField(max_length=250, verbose_name='Введите сообщение'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='name',
            field=models.CharField(max_length=250, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='number',
            field=models.CharField(max_length=250, verbose_name='Номер телефона'),
        ),
    ]
